### Success scenario
POST http://localhost:3001/api/persons/
content-type: application/json

{
  "name": "Elias Vakkuri",
  "number": "00000000"
}

### Error: Number missing
POST http://localhost:3001/api/persons/
content-type: application/json

{
  "name": "Elias Vakkuri"
}

### Error: Name missing
POST http://localhost:3001/api/persons/
content-type: application/json

{
  "number": "00000000"
}

### Error: Too short name and number
POST http://localhost:3001/api/persons/
content-type: application/json

{
  "name": "El",
  "number": "0000000"
}